aisinei/meitu/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('meitulu/', include('meituxiu.urls', namespace = 'meitu',)),
    path('novohot/', include('novohot.urls', namespace = 'novohot',)),
    path('meituri/', include('meituri.urls', namespace = 'meituri',)),
    path('mmonly/', include('mmonly.urls', namespace = 'mmonly',)),
    path('mm8/', include('mm8.urls', namespace = 'mm8',)),
    path('zhuamei5/', include('zhuamei5.urls', namespace = 'zhuamei5',)),
]

aisinei/mm8/urls.py
from django.urls import path
from . import views
app_name = '[app_name]'
urlpatterns = [
    path('', views.tag,name='main' ),
    path('<int:tagid>/', views.title, name="urltag"),
    path('<int:tagid>list/', views.list_title, name="list_title"),
    path('<int:tagid>/<int:titleid>/', views.pic, name="urltitle"),
    path('<int:tagid>/<int:titleid>/big', views.pic_big, name="urlpicbig"),
    path('search/', views.search, name="search"),

]

aisinei/mmonly/urls.py
from django.urls import path
from . import views
app_name = '[app_name]'
urlpatterns = [
    path('', views.tag,name='main' ),
    path('<int:tagid>/', views.title, name="urltag"),
    path('<int:tagid>list/', views.list_title, name="list_title"),
    path('<int:tagid>/<int:titleid>/', views.pic, name="urltitle"),
    path('<int:tagid>/<int:titleid>/big', views.pic_big, name="urlpicbig"),
    path('search/', views.search, name="search"),

]

aisinei/mmonly/models.py
from django.db import models

# Create your models here.
class MmonlyTag(models.Model):

    tag = models.CharField(max_length=20)
    def __str__(self):
        return self.tag
        
    class Meta:
        db_table = 'mmonly_tag'  # 定义数据库表名.如果不写默认为项目名_app名

class MmonlyTitle(models.Model):
    titletag= models.ForeignKey("MmonlyTag",on_delete=models.CASCADE)
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'mmonly_title'
        
class MmonlyPic(models.Model):
    pictitle = models.ForeignKey("MmonlyTitle",on_delete=models.CASCADE)
    picname = models.CharField(max_length=50)
    src = models.URLField(max_length=100)
    

    class Meta:
        db_table = 'mmonly_pic'

aisinei/mmonly/views.py
from .models import MmonlyTag, MmonlyTitle, MmonlyPic
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger,InvalidPage
from django.http import HttpResponse

def tag(request):
    taglist = MmonlyTag.objects.all()
    tags = []
    for tag in taglist:
        titlesnum = tag.mmonlytitle_set.count()
        tag_dict = {
            'tag':tag.tag,
            'num':titlesnum,
            'id':tag.id
            }
        tags.append(tag_dict)
    return render(request, 'mmonly/tag.html', {'tags':tags})


def title(request, tagid):
    #去模板取数据
    tag = get_object_or_404(MmonlyTag, id=tagid)
    titlelist = tag.mmonlytitle_set.order_by('id')
    ttlist = []
    for title in titlelist:
        pic = title.mmonlypic_set.first()
        picsnum = title.mmonlypic_set.count()

        title_dick = {
            'title': title.title,
            'src': pic.src,
            'id': title.id,
            'num': picsnum
        }
        ttlist.append(title_dick)

    paginator = Paginator(ttlist, 20, 4)
    if request.method == "GET":
        # 获取 url 后面的 page 参数的值, 首页不显示 page 参数, 默认值是 1
        page = request.GET.get('page')
        try:
            titles = paginator.page(page)
        # todo: 注意捕获异常
        except PageNotAnInteger:
            # 如果请求的页数不是整数, 返回第一页。
            titles = paginator.page(1)
        except InvalidPage:
            # 如果请求的页数不存在, 重定向页面
            return HttpResponse('找不到页面的内容')
        except EmptyPage:
            # 如果请求的页数不在合法的页数范围内，返回结果的最后一页。
            titles = paginator.page(paginator.num_pages)
    return render(request, 'mmonly/title1.html', {'titles': titles, 'tagid' :tagid, 'tag':tag})

def list_title(request, tagid):
    #去模板取数据
    tag = get_object_or_404(MmonlyTag, id=tagid)
    titlelist = tag.mmonlytitle_set.order_by('id')
    ttlist = []
    idlist = []
    for title in titlelist:
        picsnum= title.mmonlypic_set.count()
        # if picsnum == 0:
            # string = 'id={}'.format(title.id)
            # idlist.append(string)
            # idlist.append(title.id)

        title_dick = {
            'title': title.title,
            'id': title.id,
            'num': picsnum,
        }
        ttlist.append(title_dick)
    # k = ' or '.join(idlist)
    # print(k)
    # print(idlist)

    paginator = Paginator(ttlist, 20, 4)
    if request.method == "GET":
        # 获取 url 后面的 page 参数的值, 首页不显示 page 参数, 默认值是 1
        page = request.GET.get('page')
        try:
            titles = paginator.page(page)
        # todo: 注意捕获异常
        except PageNotAnInteger:
            # 如果请求的页数不是整数, 返回第一页。
            titles = paginator.page(1)
        except InvalidPage:
            # 如果请求的页数不存在, 重定向页面
            return HttpResponse('找不到页面的内容')
        except EmptyPage:
            # 如果请求的页数不在合法的页数范围内，返回结果的最后一页。
            titles = paginator.page(paginator.num_pages)
    return render(request, 'mmonly/title.html', {'titles': titles,  'tag':tag})

def pic(request, tagid, titleid,):
    tag = get_object_or_404(MmonlyTag, id=tagid)
    title = get_object_or_404(MmonlyTitle, id=titleid)
    piclist = title.mmonlypic_set.order_by('picname')
    # print(request.body)
    # print('*'*80)

    # 实现分页功能:
    paginator = Paginator(piclist, 12, 4)
    if request.method == "GET":
        page = request.GET.get('page')
        try:
            pics = paginator.page(page)
        except PageNotAnInteger:
            pics = paginator.page(1)
        except InvalidPage:
            return HttpResponse('找不到页面的内容')
        except EmptyPage:
            pics = paginator.page(paginator.num_pages)

    return render(request, 'mmonly/picture1.html', {'pics':pics,'tag':tag, 'title':title,})

def pic_big(request, tagid, titleid,):
    tag = get_object_or_404(MmonlyTag, id=tagid)
    title = get_object_or_404(MmonlyTitle, id=titleid)
    piclist = title.mmonlypic_set.order_by('picname')

    # 实现分页功能:
    paginator = Paginator(piclist, 12, 4)
    if request.method == "GET":
        # 获取 url 后面的 page 参数的值, 首页不显示 page 参数, 默认值是 1
        page = request.GET.get('page')
        try:
            pics = paginator.page(page)
        # todo: 注意捕获异常
        except PageNotAnInteger:
            # 如果请求的页数不是整数, 返回第一页。
            pics = paginator.page(1)
        except InvalidPage:
            # 如果请求的页数不存在, 重定向页面
            return HttpResponse('找不到页面的内容')
        except EmptyPage:
            # 如果请求的页数不在合法的页数范围内，返回结果的最后一页。
            pics = paginator.page(paginator.num_pages)

    return render(request, 'mmonly/picture.html', {'pics':pics,'tag':tag, 'title':title, })
def search(request):
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = '请输入关键词'
        return render(request, 'mmonly/error.html',{'error_msg':error_msg})
    titles = MmonlyTitle.objects.filter(title__icontains=q)
    number = len(titles)
    if number > 30:
        titles = titles[:30]
        error_msg = '共搜索到{}条结果,显示前30条......'.format(number,number - 30)
    

    return render(request, 'mmonly/search_title.html',{'error_msg': error_msg, 'titles': titles})


# paginator

# 可选参数¶
# orphans
# 如果您不希望最后一页包含很少的项目，请使用此选项。如果最后一页通常具有小于或等于的项目数orphans，则这些项目将被添加到上一页面（成为最后一页），而不是将这些项目自己留在页面上。例如，有23个项目，per_page=10和 orphans=3，将有两个页面; 第一页有10个项目，第二页（和最后一页）有13个项目。orphans默认为零，这意味着页面永远不会合并，最后一页可能有一个项目。
# allow_empty_first_page
# 是否允许第一页为空。如果为False和 object_list空，则会引发EmptyPage错误。

# 1.类方法

# Page.has_next()  如果有下一页，则返回True。
# Page.has_previous() 如果有上一页，返回 True。
# Page.has_other_pages() 如果有上一页或下一页，返回True。
# Page.next_page_number() 返回下一页的页码。如果下一页不存在，抛出InvlidPage异常。
# Page.previous_page_number() 返回上一页的页码。如果上一页不存在，抛出InvalidPage异常。
# Page.start_index() 返回当前页上的第一个对象，相对于分页列表的所有对象的序号，从1开始。比如，将五个对象的列表分为每页两个对象，第二页的start_index()会返回3。
# Page.end_index() 返回当前页上的最后一个对象，相对于分页列表的所有对象的序号，从1开始。 比如，将五个对象的列表分为每页两个对象，第二页的end_index() 会返回 4。

# 2.类属型

# Page.object_list 当前页上所有对象的列表。
# Page.number 当前页的序号，从1开始。
# Page.paginator 相关的Paginator对象。

# 三.非法页面处理

# InvalidPage(Exception): 异常的基类，当paginator传入一个无效的页码时抛出。
# Paginator.page()放回在所请求的页面无效（比如不是一个整数）时，或者不包含任何对象时抛出异常。通常，捕获InvalidPage异常就够了，但是如果你想更加精细一些，可以捕获以下两个异常之一：

# exception PageNotAnInteger，当向page()提供一个不是整数的值时抛出。
# exception EmptyPage，当向page()提供一个有效值，但是那个页面上没有任何对象时抛出。
#        这两个异常都是InalidPage的子类，所以可以通过简单的except InvalidPage来处理它们。

aisinei/templates/mmonly/base.html
{% load bootstrap3 %}
{% load static %}

<!DOCTYPE html>
<html lang="zh-CN">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {#请求页面没有referer,从而获取图片,破解反盗链#}
  <meta name="referrer" content="never">
  <!-- <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mystyle.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script> -->

  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <title>mmonly</title>
</head>

<body>

  <nav class="navbar navbar-default navbar-static-top">
  
    {% block tag %}
    <li>picture</li>
    {% endblock %}
  
    <div style="float:right">
      <form class="navbar-brand" role="search" method="get" id="searchform" action="{% url 'mmonly:search' %}">
        {% csrf_token %}
        <input type="search" name="q" placeholder="Search mmonly" required>
        <button type="submit"><span class="ion-ios-search-strong">搜索</span></button>
      </form>
    </div>
  </nav>


  <br>
  <div class="container">
    {% block mainbody %}
    <p>picture</p>
    {% endblock %}
  </div>


  <footer align="center">
    <div>Copyright ©2019 Asmazz Inc. 保留所有权利。</div><br>
    <p style="margin-top:-20px; margin-bottom:20px; color:#666;">京公安网安备11010502008968 京ICP备10214630 营业执照
      无线电发射设备销售备案编号11201910351200</p>
  </footer>

</html>

aisinei/templates/mmonly/picture.html
{% extends 'mmonly/viewpages.html' %}

{% block tag %}
<a class="navbar-brand" href="{% url "mmonly:main" %}">名站导航</a>
<a class="navbar-brand" href="{% url "mmonly:urltag"  tag.id %}">{{tag.tag}}</a>
<a class="navbar-brand" href="{% url "mmonly:urltitle" tag.id title.id %}?page={{pics.number}}">预览模式</a>
{% endblock tag %}

{% block mainbody %}
<h2>{{title}}</h2>
<tbody>
    {% for item in pics%}
    <li>
        <div class="container" align="center">
            <a href="{{item.src}}" target="_blank">
                <img class="img-responsive" src="{{item.src}}" alt="{{item.picname}}">
            </a>

        </div>
    </li>
    {% endfor %}
</tbody>
{% endblock  %}


{% block pages %}
<br><br>
<div class="container">
    <li class="step-links">
        <a class='active' href="{% url "mmonly:main" %}">返回主页</a>
        <a class='active' href="{% url "mmonly:list_title"  tag.id %}">返回图片列表</a>
        <a href="{% url "mmonly:urltitle" tag.id title.id %}?page={{pics.number}}">返回预览模式</a>
    </li>
</div>

<div class="container">
    <ul class="pagination">
        <li class="previous"><a href="{% url "mmonly:urlpicbig"  tag.id title.id|add:-1 %}">上一册</a></li>
        {% if pics.has_previous %}
        <li><a href="?page={{pics.previous_page_number}}">上一页</a></li>
        {% endif %}
        {% for page_num in pics.paginator.page_range %}
        {% if page_num == pics.number %}
        <li class="active"><a href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% else %}
        <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% endif %}
        {% endfor %}
        {% if pics.has_next %}
        <li><a href="?page={{pics.next_page_number}}">下一页</a></li>
        {% endif %}
        <li class="next"><a href="{% url "mmonly:urlpicbig"  tag.id title.id|add:1 %}">下一册</a></li>
    </ul>
</div>
{% endblock  %}

aisinei/templates/mmonly/picture1.html
{% extends 'mmonly/viewpages.html' %}

{% block tag %}
<a class="navbar-brand" href="{% url "mmonly:main" %}">名站导航</a>
<a class="navbar-brand" href="{% url "mmonly:urltag" tag.id %}">{{tag.tag}}</a>
<a class="navbar-brand" href="{% url "mmonly:urlpicbig" tag.id title.id %}?page={{pics.number}}">大图模式</a>
{% endblock tag %}

{% block mainbody %}
<h2>{{title}}</h2>
<div class="row">
    {% for item in pics%}
    <div class="col-sm-6 col-md-3">
        <a href="{{item.src}}" class="thumbnail" target="_blank">
            <img src="{{item.src}}" alt="{{item.picname}}">
        </a>
    </div>
    {% endfor %}
</div>



{% endblock mainbody %}


{% block pages %}
<br><br>
<div class="container">
    <li class="step-links">
        <a class='active' href="{% url "mmonly:main" %}">返回主页</a>
        <a class='active' href="{% url "mmonly:list_title"  tag.id %}">返回图片列表</a>
        <a href="{% url "mmonly:urlpicbig" tag.id title.id %}?page={{pics.number}}">返回大图模式</a>
    </li>
</div>

<div class="container">
    <ul class="pagination">
        <li class="previous"><a href="{% url "mmonly:urltitle"  tag.id title.id|add:-1 %}">上一册</a></li>
        {% if pics.has_previous %}
        <li><a href="?page={{pics.previous_page_number}}">上一页</a></li>
        {% endif %}
        {% for page_num in pics.paginator.page_range %}
        {% if page_num == pics.number %}
        <li class="active"><a href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% else %}
        <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% endif %}
        {% endfor %}
        {% if pics.has_next %}
        <li><a href="?page={{pics.next_page_number}}">下一页</a></li>
        {% endif %}
        <li class="next"><a href="{% url "mmonly:urltitle"  tag.id title.id|add:1 %}">下一册</a></li>

    </ul>
</div>
{% endblock  %}

    {% comment %} 
    Paginator属性：
    pics.number 当前页面
    print(Paginator.count) #总数据量
    print(Paginator.num_pages) #分页数
    print(Paginator.page_range) #显示的是页数的标记 就是按钮的数目
    　　print(page2.has_next()) #是否有下一页
    print(page2.next_page_number()) #下一页的页码
    print(page2.has_previous()) #是否有上一页
    print(page2.previous_page_number()) #上一页的页码 {% endcomment %}
    {% comment %} 1.类方法

Page.has_next()  如果有下一页，则返回True。
Page.has_previous() 如果有上一页，返回 True。
Page.has_other_pages() 如果有上一页或下一页，返回True。
Page.next_page_number() 返回下一页的页码。如果下一页不存在，抛出InvlidPage异常。
Page.previous_page_number() 返回上一页的页码。如果上一页不存在，抛出InvalidPage异常。
Page.start_index() 返回当前页上的第一个对象，相对于分页列表的所有对象的序号，从1开始。比如，将五个对象的列表分为每页两个对象，第二页的start_index()会返回3。
Page.end_index() 返回当前页上的最后一个对象，相对于分页列表的所有对象的序号，从1开始。 比如，将五个对象的列表分为每页两个对象，第二页的end_index() 会返回 4。
2.类属型

Page.object_list 当前页上所有对象的列表。
Page.number 当前页的序号，从1开始。
Page.paginator 相关的Paginator对象。 {% endcomment %}

aisinei/templates/mmonly/search_title.html
{% extends 'mmonly/viewpages.html' %}
{% comment %} 继承了base.html {% endcomment %}
{% block tag %}
<a class="navbar-brand" href="{% url "mmonly:main" %}">名站导航</a>
<a class="navbar-brand" href="#">搜索结果</a>
{% endblock tag %}

{% block mainbody %}
<tbody>
    {% for title in titles %}
    <td>
        <dl>
            <dt><a href="{% url "mmonly:urltitle" title.titletag_id title.id %}" target="_blank">{{title.title}}</a>
        </dl>
    </td>
    {% endfor %}
</tbody>
<p>{{error_msg}}</p>
{% endblock mainbody %}

{% block pages %}
<br><br>
<li class="step-links">
    <a class='active' href="{% url "mmonly:main" %}">返回主页</a>
</li>
{% endblock pages %}

aisinei/templates/mmonly/tag.html
{% extends 'mmonly/base.html' %}
{% comment %} 继承了base.html {% endcomment %}

{% block tag %}
<a class="navbar-brand" href="{% url "mmonly:main" %}">名站导航</a>
{% endblock tag %}
{% block mainbody %}
<div class="row">

  <h1>mmonly</h1>
  {% for tag in tags %}
  <div class="col-sm-6 col-md-3">

    <div class="list-group-item">
      <!-- <h4><a href="{% url "mmonly:urltag" tag.id %}">{{tag.tag}}</a></h4> -->
      <h3><a href="{% url "mmonly:urltag" tag.id %}">{{tag.tag}}</a></h3>
      <p>共有{{tag.num}}套</p>
      <a href="{% url "mmonly:list_title" tag.id %}" class="btn btn-default" role="button" target="_blank">列表</a>
      <a href="{% url "mmonly:urltag" tag.id %}" class="btn btn-default" role="button" target="_blank">
        预览
      </a>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock  %}

aisinei/templates/mmonly/title.html
{% extends 'mmonly/viewpages.html' %}
{# 继承了base.html #}
{% block tag %}
<a class="navbar-brand" href="{% url "mmonly:main" %}">名站导航</a>
<a class="navbar-brand" href="{% url "mmonly:urltag" tag.id %}">{{tag.tag}}</a>
{% endblock tag %}

{% block mainbody %}
<tbody>
    {% for title in titles %}
    <td>
        <dl>
            <dt><a href="{% url "mmonly:urlpicbig" tag.id title.id %}" target="_blank">{{title.title}}</a>
            <p>共{{title.num}}张</p>
        </dl>
    </td>
    {% endfor %}
</tbody>
{% endblock mainbody %}


{% block pages %}
<br><br>
<li class="step-links">
    <a class='active' href="{% url "mmonly:main" %}">返回主页</a>
</li>
<div class="container">
    {% comment %} <div class="pagination center aligned menu"> {% endcomment %}
        <ul class="pagination">

            {% if titles.has_previous %}
            <li><a href="?page={{titles.previous_page_number}}">上一页</a></li>
            {% endif %}
            {% for page_num in titles.paginator.page_range %}

            {% if page_num == titles.number %}
            <li class="active"><a href="?page={{ page_num }}">{{ page_num }}</a></li>
            {% else %}
            <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
            {% endif %}
            {% endfor %}
            {% if titles.has_next %}
            <li><a href="?page={{titles.next_page_number}}">下一页</a></li>
            {% endif %}
        </ul>
    </div>
    {% endblock  %}

aisinei/templates/mmonly/title1.html
{% extends 'mmonly/viewpages.html' %}
{% comment %} 继承了base.html {% endcomment %}

{% block tag %}
<a class="navbar-brand" href="{% url "mmonly:main" %}">名站导航</a>
<a class="navbar-brand" href="{% url "mmonly:list_title" tag.id %}">{{tag.tag}}</a>
{% endblock tag %}
{% block mainbody %}
<div class="row">
    {% for title in titles %}

    <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
            <a href="{% url "mmonly:urlpicbig" tagid title.id %}" target="_blank">
                <img src="{{title.src}}" alt="{{title.title}}">
            </a>
            <div class="caption">
                <h5><a href="{% url "mmonly:urlpicbig" tag.id title.id %}" target="_blank">{{title.title}}</a></h5>
                <h6>{{title.num}}张</h6>

                <p>
                    <a href="{% url "mmonly:urltitle" tag.id title.id %}" class="btn btn-primary" role="button"
                        target="_blank">
                        预览模式
                    </a>
                    <a href="{% url "mmonly:urlpicbig" tag.id title.id %}" class="btn btn-default" role="button"
                        target="_blank">
                        大图模式
                    </a>
                </p>
            </div>
        </div>
    </div>

    {% endfor %}
</div>

{% endblock mainbody  %}




{% block pages %}
<br><br>
<li class="step-links">
    <a class='active' href="{% url "mmonly:main" %}">返回主页</a>
</li>
<div class="container">
    <ul class="pagination">

        {% if titles.has_previous %}
        <li><a href="?page={{titles.previous_page_number}}">上一页</a></li>
        {% endif %}
        {% for page_num in titles.paginator.page_range %}

        {% if page_num == titles.number %}
        <li class="active"><a href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% else %}
        <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% endif %}
        {% endfor %}
        {% if titles.has_next %}
        <li><a href="?page={{titles.next_page_number}}">下一页</a></li>
        {% endif %}
    </ul>
</div>
{% endblock  %}

aisinei/templates/mmonly/viewpages.html
{% comment %} {% load staticfiles %} {% endcomment %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="zh-CN">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {#请求页面没有referer,从而获取图片,破解反盗链#}
  <meta name="referrer" content="never">
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  {% comment %} <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mystyle.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script> {% endcomment %}
  <title>mmonly</title>
</head>

<body>
  <!-- Static navbar导航栏 -->
  <nav class="navbar navbar-default navbar-static-top">

    {% block tag %}
    <li>picture</li>
    {% endblock %}

    <div style="float:right">
      <form class="navbar-brand" role="search" method="get" id="searchform" action="{% url 'mmonly:search' %}">
        {% csrf_token %}
        <input type="search" name="q" placeholder="Search mmonly" required>
        <button type="submit"><span class="ion-ios-search-strong">搜索</span></button>
      </form>
    </div>
  </nav>


  <br>
  <div class="container">
    {% block mainbody %}
    <p>picture</p>
    {% endblock %}
  </div>
  <div class="pages" , align="center">
    {% block pages%}
    <p>pages</p>
    {% endblock %}
  </div>
</body>


<footer class="footer" align="center">
  <div>Copyright ©2019 Asmazz Inc. 保留所有权利。</div><br>
  <p style="margin-top:-20px; margin-bottom:20px; color:#666;">京公安网安备11010502008968 京ICP备10214630 营业执照
    无线电发射设备销售备案编号11201910351200</p>
</footer>

</html>