aisinei/meitu/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('meitulu/', include('meituxiu.urls', namespace = 'meitu',)),
    path('novohot/', include('novohot.urls', namespace = 'novohot',)),
    path('meituri/', include('meituri.urls', namespace = 'meituri',)),
    path('mmonly/', include('mmonly.urls', namespace = 'mmonly',)),
    path('mm8/', include('mm8.urls', namespace = 'mm8',)),
    path('zhuamei5/', include('zhuamei5.urls', namespace = 'zhuamei5',)),
]

aisinei/meituxiu/urls.py
from django.urls import path
from . import views
app_name = '[app_name]'
urlpatterns = [
    path('', views.tag,name='main' ),
    path('<int:tagid>/', views.title, name="urltag"),
    path('<int:tagid>list/', views.list_title, name="list_title"),
    path('<int:tagid>/<int:titleid>/', views.pic, name="urltitle"),
    path('<int:tagid>/<int:titleid>/big', views.pic_big, name="urlpicbig"),
    path('search/', views.search, name="search"),
]

aisinei/mm8/urls.py
from django.urls import path
from . import views
app_name = '[app_name]'
urlpatterns = [
    path('', views.tag,name='main' ),
    path('<int:tagid>/', views.title, name="urltag"),
    path('<int:tagid>list/', views.list_title, name="list_title"),
    path('<int:tagid>/<int:titleid>/', views.pic, name="urltitle"),
    path('<int:tagid>/<int:titleid>/big', views.pic_big, name="urlpicbig"),
    path('search/', views.search, name="search"),

]

aisinei/meituxiu/models.py
from django.db import models

# Create your models here.
class MeituTag(models.Model):

    tag = models.CharField(max_length=20)

    def __str__(self):
        return self.tag

    class Meta:
        # abstract = True
        db_table = 'meitu_tag'  # 定义数据库表名.如果不写默认为项目名_app名

class MeituTitle(models.Model):
    titletag= models.ForeignKey("MeituTag",on_delete=models.CASCADE)
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    class Meta:
        # abstract = True
        db_table = 'meitu_title'
class MeituPic(models.Model):
    # pictag = models.ForeignKey("MeituTag",on_delete=models.CASCADE)
    pictitle = models.ForeignKey("MeituTitle",on_delete=models.CASCADE)
    picname = models.CharField(max_length=100)
    src = models.CharField(max_length=100)
    picstore = models.CharField(max_length=200)
    

    class Meta:
        db_table = 'meitu_pic'

aisinei/meituxiu/views.py
from .models import MeituTag, MeituTitle, MeituPic
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger,InvalidPage
from django.http import HttpResponse

# Create your views here.

def tag(request):
    taglist = MeituTag.objects.all()
    return render(request, 'meituxiu/tag.html', {'tags':taglist})


def title(request, tagid):
    #去模板取数据
    # tag = MeituTag.objects.get(id=tagid )
    tag = get_object_or_404(MeituTag, pk=tagid)
    titlelist = tag.meitutitle_set.order_by('id')
    ttlist = []
    for title in titlelist:
        # print(title.id)
        pic = title.meitupic_set.first()
        # order_by('picname')[0]
        # pic = MeituPic.objects.get( pictitle=title.id)
        # print(pic.src)
        adick = {
            'title': title.title,
            'src': pic.src,
            'id': title.id
        }
        ttlist.append(adick)

    # titlelist = MeituTitle.objects.filter(titletag_id=tagid)#.order_by('title')
    paginator = Paginator(ttlist, 20, 4)
    # paginator = Paginator(titlelist, 20)
    if request.method == "GET":
        # 获取 url 后面的 page 参数的值, 首页不显示 page 参数, 默认值是 1
        page = request.GET.get('page')
        try:
            titles = paginator.page(page)
        # todo: 注意捕获异常
        except PageNotAnInteger:
            # 如果请求的页数不是整数, 返回第一页。
            titles = paginator.page(1)
        except InvalidPage:
            # 如果请求的页数不存在, 重定向页面
            return HttpResponse('找不到页面的内容')
        except EmptyPage:
            # 如果请求的页数不在合法的页数范围内，返回结果的最后一页。
            titles = paginator.page(paginator.num_pages)
    return render(request, 'meituxiu/title1.html', {'titles': titles, 'tagid' :tagid, 'tag':tag})

def list_title(request, tagid):
    #去模板取数据
    tag = get_object_or_404(MeituTag, pk=tagid)
    titlelist = tag.meitutitle_set.order_by('id')
    ttlist = []
    idlist = []
    for title in titlelist:
        picsnum= title.meitupic_set.count()

        if picsnum == 0:
            string = 'id={}'.format(title.id)
            idlist.append(string)
            # idlist.append(title.id)

        title_dick = {
            'title': title.title,
            'id': title.id,
            'num': picsnum,
        }
        ttlist.append(title_dick)

    k = ' or '.join(idlist)
    # with open('/Users/mac/python/mypython/titleid.txt','a') as f:
    #     f.write(k)
    print(k)
    # print(idlist)

    paginator = Paginator(ttlist, 20, 4)
    if request.method == "GET":
        # 获取 url 后面的 page 参数的值, 首页不显示 page 参数, 默认值是 1
        page = request.GET.get('page')
        try:
            titles = paginator.page(page)
        # todo: 注意捕获异常
        except PageNotAnInteger:
            # 如果请求的页数不是整数, 返回第一页。
            titles = paginator.page(1)
        except InvalidPage:
            # 如果请求的页数不存在, 重定向页面
            return HttpResponse('找不到页面的内容')
        except EmptyPage:
            # 如果请求的页数不在合法的页数范围内，返回结果的最后一页。
            titles = paginator.page(paginator.num_pages)
    return render(request, 'meituxiu/title.html', {'titles': titles,  'tag':tag})
def pic(request, tagid, titleid,):
    # piclist = MeituPic.objects.filter(pictitle_id=titleid)
    # title = MeituTitle.objects.get(id=titleid)
    title = get_object_or_404(MeituTitle, pk=titleid)
    piclist = title.meitupic_set.all()#.order_by('picname')
    print(request.body)
    print('*'*80)

    # 实现分页功能:
    paginator = Paginator(piclist, 12, 4)
    if request.method == "GET":
        # 获取 url 后面的 page 参数的值, 首页不显示 page 参数, 默认值是 1
        page = request.GET.get('page')
        try:
            pics = paginator.page(page)
        # todo: 注意捕获异常
        except PageNotAnInteger:
            # 如果请求的页数不是整数, 返回第一页。
            pics = paginator.page(1)
        except InvalidPage:
            # 如果请求的页数不存在, 重定向页面
            return HttpResponse('找不到页面的内容')
        except EmptyPage:
            # 如果请求的页数不在合法的页数范围内，返回结果的最后一页。
            pics = paginator.page(paginator.num_pages)

    return render(request, 'meituxiu/picture1.html', {'pics':pics,'tag':tagid, 'title':title,'titleid':titleid, })

def pic_big(request, tagid, titleid,):

    title = get_object_or_404(MeituTitle, pk=titleid)
    piclist = title.meitupic_set.all()#.order_by('picname')

    # 实现分页功能:
    paginator = Paginator(piclist, 12, 4)
    if request.method == "GET":
        # 获取 url 后面的 page 参数的值, 首页不显示 page 参数, 默认值是 1
        page = request.GET.get('page')
        try:
            pics = paginator.page(page)
        # todo: 注意捕获异常
        except PageNotAnInteger:
            # 如果请求的页数不是整数, 返回第一页。
            pics = paginator.page(1)
        except InvalidPage:
            # 如果请求的页数不存在, 重定向页面
            return HttpResponse('找不到页面的内容')
        except EmptyPage:
            # 如果请求的页数不在合法的页数范围内，返回结果的最后一页。
            pics = paginator.page(paginator.num_pages)

    return render(request, 'meituxiu/picture.html', {'pics':pics,'tag':tagid, 'title':title,'titleid':titleid, })

def search(request):
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = '请输入关键词'
        return render(request, 'meituxiu/error.html',{'error_msg':error_msg})
    titles = MeituTitle.objects.filter(title__icontains=q)
    number = len(titles)
    if number > 30:
        titles = titles[:30]
        error_msg = '共搜索到{}条结果,还有{}条结果未显示......'.format(number,number - 30)
 
    return render(request, 'meituxiu/search_title.html', {'error_msg': error_msg, 'titles': titles})

aisinei/templates/meituxiu/base.html
{#{% load staticfiles %}#}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="zh-CN">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {#请求页面没有referer,从而获取图片,破解反盗链#}
  <meta name="referrer" content="never">
  {% comment %}
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mystyle.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script> {% endcomment %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <title>meitulu</title>
</head>

<body>
  <br>
  <div class="container">
    {% block mainbody %}
    <p>picture</p>
    {% endblock %}
  </div>


  <footer align="center">
    <div>Copyright ©2019 Asmazz Inc. 保留所有权利。</div><br>
    <p style="margin-top:-20px; margin-bottom:20px; color:#666;">京公安网安备11010502008968 京ICP备10214630 营业执照
      无线电发射设备销售备案编号11201910351200</p>
  </footer>

</html>

aisinei/templates/meituxiu/picture.html
{% extends 'meituxiu/viewpages.html' %}

{% block tag %}
<a class="navbar-brand" href="{% url "meitu:main" %}">名站导航</a>
<a class="navbar-brand" href="{% url "meitu:urltag"  tag %}">美图列表</a>
<a class="navbar-brand" href="{% url "meitu:urltitle" tag titleid %}?page={{pics.number}}">预览模式</a>
{% endblock tag %}

{% block mainbody %}
<h2>{{title}}</h2>
<tbody>
    {% for item in pics%}
    <li>
        <div class="container" align="center">
            <a href="{{item.src}}" target="_blank">
                <img class="img-responsive" src="{{item.src}}" alt="{{item.picname}}">
            </a>

        </div>
    </li>
    {% endfor %}
</tbody>
{% endblock  %}


{% block pages %}
<br><br>
<div class="container">
    <li class="step-links">
        <a class='active' href="{% url "meitu:main" %}">返回主页</a>
        <a class='active' href="{% url "meitu:urltag"  tag %}">返回图片列表</a>
        <a href="{% url "meitu:urltitle" tag titleid %}?page={{pics.number}}">返回预览模式</a>
    </li>
</div>

<div class="container">
    <ul class="pagination">
        <li class="previous"><a href="{% url "meitu:urlpicbig"  tag titleid|add:-1 %}">上一册</a></li>
        {% if pics.has_previous %}
        <li><a href="?page={{pics.previous_page_number}}">上一页</a></li>
        {% endif %}
        {% for page_num in pics.paginator.page_range %}
        {% if page_num == pics.number %}
        <li class="active"><a href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% else %}
        <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% endif %}
        {% endfor %}
        {% if pics.has_next %}
        <li><a href="?page={{pics.next_page_number}}">下一页</a></li>
        {% endif %}
        <li class="next"><a href="{% url "meitu:urlpicbig"  tag titleid|add:1 %}">下一册</a></li>

    </ul>
</div>
{% endblock  %}

aisinei/templates/meituxiu/picture1.html
{% extends 'meituxiu/viewpages.html' %}

{% block tag %}
<a class="navbar-brand" href="{% url "meitu:main" %}">名站导航</a>
<a class="navbar-brand" href="{% url "meitu:urltag"  tag %}">美图列表</a>
<a class="navbar-brand" href="{% url "meitu:urlpicbig" tag titleid %}?page={{pics.number}}">大图模式</a>
{% endblock tag %}

{% block mainbody %}
<h2>{{title}}</h2>
<div class="row">
    {% for item in pics%}
    <div class="col-sm-6 col-md-3">
        <a href="{{item.src}}" class="thumbnail" target="_blank">
            <img src="{{item.src}}" alt="{{item.picname}}">
        </a>
    </div>
    {% endfor %}
</div>
{% endblock mainbody %}


{% block pages %}
<br><br>
<div class="container">
    <li class="step-links">
        <a class='active' href="{% url "meitu:main" %}">返回主页</a>
        <a class='active' href="{% url "meitu:urltag"  tag %}">返回图片列表</a>
        <a href="{% url "meitu:urlpicbig" tag titleid %}?page={{pics.number}}">返回大图模式</a>
    </li>
</div>

<div class="container">
    <ul class="pagination">
        <li class="previous"><a href="{% url "meitu:urltitle"  tag titleid|add:-1 %}">上一册</a></li>
        {% if pics.has_previous %}
        <li><a href="?page={{pics.previous_page_number}}">上一页</a></li>
        {% endif %}
        {% for page_num in pics.paginator.page_range %}
        {% if page_num == pics.number %}
        <li class="active"><a href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% else %}
        <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% endif %}
        {% endfor %}
        {% if pics.has_next %}
        <li><a href="?page={{pics.next_page_number}}">下一页</a></li>
        {% endif %}
        <li class="next"><a href="{% url "meitu:urltitle"  tag titleid|add:1 %}">下一册</a></li>

    </ul>
</div>
{% endblock pages %}

aisinei/templates/meituxiu/search_title.html
{% extends 'meituxiu/viewpages.html' %}
{% block tag %}
<a class="navbar-brand" href="{% url "meitu:main" %}">名站导航</a>
<a class="navbar-brand" href="#">搜索结果</a>
{% endblock tag %}

{% block mainbody %}
<tbody>
    {% for title in titles %}
    <td>
        <dl>
            <dt><a href="{% url "meitu:urltitle" title.titletag_id title.id %}" target="_blank">{{title.title}}</a>
        </dl>
    </td>
    {% endfor %}
</tbody>
<p>{{error_msg}}</p>
{% endblock mainbody %}

{% block pages %}
<br><br>
<li class="step-links">
    <a class='active' href="{% url "meitu:main" %}">返回主页</a>
</li>
<div class="container">
    {% comment %} <div class="pagination center aligned menu"> {% endcomment %}
        <ul class="pagination">

            {% if titles.has_previous %}
            <li><a href="?page={{titles.previous_page_number}}">上一页</a></li>
            {% endif %}
            {% for page_num in titles.paginator.page_range %}

            {% if page_num == titles.number %}
            <li class="active"><span>{{ page_num }}</span></li>
            {% else %}
            <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
            {% endif %}
            {% endfor %}
            {% if titles.has_next %}
            <li><a href="?page={{titles.next_page_number}}">下一页</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock pages %}

aisinei/templates/meituxiu/tag.html
{% extends 'meituxiu/base.html' %}
{% comment %} 继承了base.html {% endcomment %}

{% block tag %}
<a class="navbar-brand" href="{% url "meitu:main" %}">名站导航</a>
{% endblock tag %}
{% block mainbody %}
<div class="row">

    <h1>meitu</h1>
    {% for tag in tags %}
    <div class="col-sm-6 col-md-3">

        <div class="list-group-item">
            <!-- <h4><a href="{% url "meitu:urltag" tag.id %}">{{tag.tag}}</a></h4> -->
            <h3><a href="{% url "meitu:urltag" tag.id %}">{{tag.tag}}</a></h3>
            <!-- <p>共有{{tag.num}}套</p> -->
            <a href="{% url "meitu:list_title" tag.id %}" class="btn btn-default" role="button" target="_blank">列表</a>
            <a href="{% url "meitu:urltag" tag.id %}" class="btn btn-default" role="button" target="_blank">
                预览
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock  %}

aisinei/templates/meituxiu/tag_old.html
{% extends 'meituxiu/base.html' %}
{% comment %} 继承了base.html {% endcomment %}

    {% block mainbody %}
    <div class="row">

    <h1>meitu</h1>
         {% for tag in tags %}
    <div class="col-sm-6 col-md-3">

<h4><a href="{% url "meitu:urltag" tag.id %}" class="list-group-item">{{tag.tag}}</a></h4>
</div>
         {% endfor %}
  </div>
    {% endblock  %}

    {% comment %} <div class="list-group">
  <a href="#" class="list-group-item list-group-item-success">Dapibus ac facilisis in</a>
  <a href="#" class="list-group-item list-group-item-info">Cras sit amet nibh libero</a>
  <a href="#" class="list-group-item list-group-item-warning">Porta ac consectetur ac</a>
  <a href="#" class="list-group-item list-group-item-danger">Vestibulum at eros</a>
</div> {% endcomment %}

aisinei/templates/meituxiu/title.html
{% extends 'meituxiu/viewpages.html' %}
{# 继承了base.html #}

{% block title %}
<title>{{tag.tag}}</title>
{% endblock title %}

{% block tag %}
<a class="navbar-brand" href="{% url "meitu:main" %}">名站导航</a>
<a class="navbar-brand" href="{% url "meitu:urltag" tag.id %}">{{tag.tag}}</a>
{% endblock tag %}

{% block mainbody %}
<tbody>
    {% for title in titles %}
    <td>
        <dl>
            <dt><a href="{% url "meitu:urlpicbig" tag.id title.id %}" target="_blank">{{title.title}}</a>
                <p>共{{title.num}}张</p>
        </dl>
    </td>
    {% endfor %}
</tbody>
{% endblock mainbody %}


{% block pages %}
<br><br>
<li class="step-links">
    <a class='active' href="{% url "meitu:main" %}">返回主页</a>
</li>
<div class="container">
    {% comment %} <div class="pagination center aligned menu"> {% endcomment %}
        <ul class="pagination">

            {% if titles.has_previous %}
            <li><a href="?page={{titles.previous_page_number}}">上一页</a></li>
            {% endif %}
            {% for page_num in titles.paginator.page_range %}

            {% if page_num == titles.number %}
            <li class="active"><span>{{ page_num }}</span></li>
            {% else %}
            <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
            {% endif %}
            {% endfor %}
            {% if titles.has_next %}
            <li><a href="?page={{titles.next_page_number}}">下一页</a></li>
            {% endif %}
        </ul>
    </div>
    {% endblock  %}

aisinei/templates/meituxiu/title1.html
{% extends 'meituxiu/viewpages.html' %}
{% comment %} 继承了base.html {% endcomment %}

{% block tag %}
<a class="navbar-brand" href="{% url "meitu:main" %}">名站导航</a>
<a class="navbar-brand" href="#">{{tag.tag}}</a>
{% endblock tag %}
{% block mainbody %}
<div class="row">
    {% for title in titles %}

    <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
            <a href="{% url "meitu:urlpicbig" tagid title.id %}" target="_blank">
                <img src="{{title.src}}" alt="{{title.title}}">
            </a>
            <div class="caption">
                <h5><a href="{% url "meitu:urlpicbig" tagid title.id %}" target="_blank">{{title.title}}</a></h5>
                <p>
                    <a href="{% url "meitu:urltitle" tagid title.id %}" class="btn btn-primary" role="button"
                        target="_blank">
                        预览模式
                    </a>
                    <a href="{% url "meitu:urlpicbig" tagid title.id %}" class="btn btn-default" role="button"
                        target="_blank">
                        大图模式
                    </a>
                </p>
            </div>
        </div>
    </div>

    {% endfor %}
</div>

{% endblock mainbody  %}




{% block pages %}
<br><br>
<li class="step-links">
    <a class='active' href="{% url "meitu:main" %}">返回主页</a>
</li>
<div class="container">
    <ul class="pagination">

        {% if titles.has_previous %}
        <li><a href="?page={{titles.previous_page_number}}">上一页</a></li>
        {% endif %}
        {% for page_num in titles.paginator.page_range %}

        {% if page_num == titles.number %}
        <li class="active"><a href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% else %}
        <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% endif %}
        {% endfor %}
        {% if titles.has_next %}
        <li><a href="?page={{titles.next_page_number}}">下一页</a></li>
        {% endif %}
    </ul>
</div>
{% endblock  %}

{% comment %}
注释多行
{% endcomment %}
{# 注释单行 #}

aisinei/templates/meituxiu/viewpages.html
{#{% load staticfiles %}#}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {#请求页面没有referer,从而获取图片,破解反盗链#}
  <meta name="referrer" content="never">

    {% bootstrap_css %}
    {% bootstrap_javascript %}
  <title>meitulu</title>
</head>
<body>
<!-- Static navbar导航栏 -->
<nav class="navbar navbar-default navbar-static-top">

        {% block tag %}
    <li>picture</li>
    {% endblock %}

    <div style="float:right">
    <form class="navbar-brand" role="search" method="get" id="searchform" action="{% url 'meitu:search' %}">
      {% csrf_token %}
      <input type="search" name="q" placeholder="Search aisinei" required>
      <button type="submit"><span class="ion-ios-search-strong">搜索</span></button>
    </form>
    </div>
  </nav>


<br>
<div  class="container">
    {% block mainbody %}
    <p>picture</p>
    {% endblock %}
</div>
<div class="pages", align="center">
    {% block pages%}
    <p>pages</p>
    {% endblock %}
</div>
</body>


<footer class="footer" align="center">
<div >Copyright ©2019 Asmazz Inc. 保留所有权利。</div><br>
<p style="margin-top:-20px; margin-bottom:20px; color:#666;">京公安网安备11010502008968 京ICP备10214630 营业执照 无线电发射设备销售备案编号11201910351200</p>
</footer>
</html>